### PR TITLE
tpmtest: fix simple TPM2B initialization issues

### PR DESCRIPTION
**Pull request by gwei3**
fixed one more bug, and updated to use INIT_SIMPLE_TPM2B_SIZE for the initialization.

### CODE REVIEW

**Comment by wcarthur1** [comment]
Jimmy, you also need to do this in the test\common\sample directory.

**Comment by gwei3** [comment]
updated the sample code.

**Comment by wcarthur1** [comment]
Jimmy, good job on sample code:  you caught a couple cases I didn't update to use the macro.
On the other hand:  I looked at tpmtest and you missed a lot of the cases that need to add the initialization of the TPM2B size field.  some examples:  look at lines 633, 639, and 652 of tpmtest.cpp and compare to what I did in tpmclient.cpp.  You'll need to go through the whole of tpmtest.cpp and make sure you did this everywhere I did it in tpmclient.cpp.  Using a good side by side smart compare tool like Araxis Merge or Beyond Compare will help you in this.

**Comment by gwei3** [comment]
Finished.

**Pull request merged**
