### PR TITLE
resourcemgr: Default to simulator port when connecting to the simulator.

### PR DESCRIPTION
**Pull request by flihp**
This regression brought to you by
6feb976cc62bab3a3ec4687bcf308c4e703f27ce.

Signed-off-by: Philip Tricca <philip.b.tricca@intel.com>

### CODE REVIEW

**Comment by wcarthur1** [comment]
Philip,

It needs to be changed in one other place too.  The help message defaults for the simulator and RM ports aren't correct.

**Comment by flihp** [comment]
Not sure I follow @wcarthur1. Nothing in the help text was changed in 6feb976cc62bab3a3ec4687bcf308c4e703f27ce so I'm a bit lost as to what you want. The current help output from master is:

```
Resource manager daemon, Version 0.85
Usage:  resourcemgr [-sim] [-tpmhost hostname|ip_addr] [-tpmport port] [-apport port]

where:

-sim tells resource manager to communicate with TPM 2.0 simulator (default: communicates with local TPM; must be specified for running on Windows)
-tpmhost specifies the host IP address for communicating with the TPM (default: 127.0.0.1; only valid if -sim used)
-tpmport specifies the port number for communicating with the TPM (default: 2321; only valid if -sim used)
-apport specifies the port number for communicating with the calling application (default: 2323)
```

Which values aren't correct?

**Comment by wcarthur1** [comment]
My mistake on last comment.

**Comment by flihp** [comment]
Thanks @wcarthur1 !

**Pull request merged**
