### PR TITLE
RM: make physical TPM case working again

### LINKED ISSUE #199: Resource Manager hang
I'm getting this second hand from a few different sources so this may not be completely accurate. Bear with me.

It looks like 3c0debc broke something when the resource manager is connected to a proper TPM instead of the simulator. That's my commit so I'm digging into this in the next few days.

### PR DESCRIPTION
**Pull request by gwei3**
resolve #199.

### CODE REVIEW

**Comment by snits** [comment]
Tested on my system here and both resourcemgr runs, and tpmtest now runs successfully.

**Comment by gwei3** [comment]
thanks for the quick verification��

**Comment by wcarthur1** [comment]
I'm going to ask Philip to look at this.
Thanks for looking at this.

**Comment by flihp** [comment]
This is a great patch @gwei3. Thanks for taking care of this. I added some additional information to your commit message but that's it.

**Pull request closed without merging**
