### PR TITLE
Tcti tests

### PR DESCRIPTION
**Pull request by wcarthur1**
Added TCTI tests and fixed all bugs found.
Changed readme.pdf to *.md files.

### CODE REVIEW

**Comment by wcarthur1** [comment]
Jimmy, can you take a look at this?

**Comment by wcarthur1** [comment]
Jimmy, should I assign someone else to this?  Or just merge it myself?  I've got a lot of other changes that I need to create a pull request for that depend on these changes.

**Comment by gwei3** [comment]
Will, I will try to do it this afternoon. Sorry for delayed response since I am still in trainings outside.

Jimmy

-----Original Message-----

**Comment by gwei3** [comment]
Things look fine for me.

**Pull request merged**
