### PR TITLE
Ubuntu dependencies in INSTALL files

### PR DESCRIPTION
**Pull request by pdxjohnny**
Added Dockerfile to allow for building in a container to
help those who are running on a system with hard to find
packages.

Signed-off-by: John Andersen <john.s.andersen@intel.com>

### CODE REVIEW

**Comment by pdxjohnny** [comment]
Me and four other people had issues with installing so I figured yes it's already in the install but better to make it even more of a no brainer on how to install :)

**Comment by rethink-neil** [comment]
Why `ubuntu:trusty` as base image?

**Comment by pdxjohnny** [comment]
@rethink-neil because I basically replicated the `.travis.yml` :smile:

**Comment by flihp** [comment]
LGTM. Will probably rearrange things a bit to remove the duplicate INSTALL (must have been left behind when I converted to INSTALL.md) and maybe to move the dockerfile to a `contrib` directory or something similar.

**Pull request merged**
