### PR TITLE
Windows TBS driver

### PR DESCRIPTION
**Pull request by awisz**
Windows TBS driver.

### CODE REVIEW

**Comment by wcarthur1** [comment]
Thanks for developing this--a very welcome addition to this code base.  Some questions:
1.  Has this been integrated with the tpmclient and tpmtest programs and tested?  If so, where are those changes and did those tests pass when communicating with a Windows system with TPM 2.0 installed?  If not, someone will need to do this work.
2.  I recently completed some mods to TCTI modules for error and bounds checking.  See my TCTI pull request.  Someone will need to port those changes to your TCTI module.  Is that something you're up for.

One more quick question:  who do you work for?  No particular reason I'm asking, just like to know something about the folks working on this.

Thanks,
Will Arthur
Intel Corporation

**Comment by wcarthur1** [comment]
Look at my most recent changes to the localtpm files.  These changes need to be ported to you TBS interface.  then we can merge your changes in.

**Comment by wcarthur1** [comment]
Is porting latest changes to localtpm files to your TBS TCTI interface something you're going to be able to do?  If not, I'll find someone else to do it.

**Comment by flihp** [comment]
No motion on this in nearly a year. I'm closing it to reduce clutter since windows support hasn't happened in a real way. There's a link to this PR in the Windows Support milestone https://github.com/01org/TPM2.0-TSS/milestone/9 so if someone is motivated to do the work this PR will be reachable from there.

**Pull request closed without merging**
