### PR TITLE
Socket global

### PR DESCRIPTION
**Pull request by flihp**
This series of patches removes global data from the socket code, including the socket TCTI.

### CODE REVIEW

**Comment by wcarthur1** [comment]
In recBytes and sendBytes, you removed the debug messages that were being printed out when an error occurs.  Typically, those are extraordinary events, and I'd like definitely like to see the error details when they happen.  Maybe I'm missing something, but is there some compelling reason to remove these?

**Comment by wcarthur1** [comment]
Built and tested it on Linux and Windows.  Just waiting for answer/resolution to issue above.

**Comment by flihp** [comment]
assigned this back to myself since the merge I did this morning requires fixups

**Comment by flihp** [comment]
Rebase accomplished

**Comment by wcarthur1** [comment]
Philip,

That still has the compiler warning on line #61 of tcti_socket.cpp that gets turned into an error when building with –Wall –Werror flags.

I’m out of time today…you can fix it or I can fix it on Monday (and hopefully get it merged in without problems).

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by wcarthur1** [comment]
Been futzing around with this for 45 minutes now without success.

We either need to meet or you need to fix this and merge the changes.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

From: Arthur, Will C
Sent: Friday, April 8, 2016 6:11 PM
To: 01org/TPM2.0-TSS <reply@reply.github.com>
Subject: RE: [01org/TPM2.0-TSS] Socket global (#174)

Philip,

That still has the compiler warning on line #61 of tcti_socket.cpp that gets turned into an error when building with –Wall –Werror flags.

I’m out of time today…you can fix it or I can fix it on Monday (and hopefully get it merged in without problems).

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by wcarthur1** [comment]
Actually there are other warnings being turned into errors.

I’m going to accept your PR as is, then create a new one to fix the issues with warnings.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

From: Arthur, Will C
Sent: Monday, April 11, 2016 9:16 AM
To: '01org/TPM2.0-TSS' <reply@reply.github.com>
Subject: RE: [01org/TPM2.0-TSS] Socket global (#174)

Been futzing around with this for 45 minutes now without success.

We either need to meet or you need to fix this and merge the changes.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

From: Arthur, Will C
Sent: Friday, April 8, 2016 6:11 PM
To: 01org/TPM2.0-TSS <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: RE: [01org/TPM2.0-TSS] Socket global (#174)

Philip,

That still has the compiler warning on line #61 of tcti_socket.cpp that gets turned into an error when building with –Wall –Werror flags.

I’m out of time today…you can fix it or I can fix it on Monday (and hopefully get it merged in without problems).

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Pull request merged**
