### PR TITLE
Big change to better align with spec for exposed headers and structures.

### LINKED ISSUE #100: don't install util headers
Had a chat with @wcarthur1 today and it looks like my efforts to install the SAPI headers were a bit overly ambitious. Some of the headers we're now installing aren't intended for public consumption. This issue is to track identifying which headers shouldn't be installed and then backing them out of the build / install target.

### LINKED ISSUE #102: consistent naming of tcti headers
The headers for the TCTIs we provide should be named consistently. The library they're built into, as well as the directory they're installed into need to be renamed as part of the overall cleanup effort.

This ticket covers the following reorg:
tpm2tcti/localtpm.h -> tcti/tpmdevice.h
tpm2tcti/tpmsocket.h -> tcti/tpmsocket.h
libtpm2tctidev.so -> libtctidev.so
libtpm2tctisock.so -> libtctisock.so

### LINKED ISSUE #103: rename tpm2tss with tss2
Based on feedback from the TCG working group we need to make a few changes to the way we're naming include directories and libraries.

$(includedir)/tpm2tss -> $(includedir)/tss2
$(libdir)/libtpm2tss.so -> $(libdir)/libtss2.so

This will break all code that uses the TPM2.0-TSS currently. Apologies for punishing early adopters further.

### PR DESCRIPTION
**Pull request by flihp**
Top level changes:
- Rename the tpm2sapi and tpm2tcti include directory to the preferred tss2
  and tcti respectively.
- Move headers that aren't part of the spec out of the installed system
  directory and remove the tss2_ prefix from them. They're back in the
  sapi include directory. There are still a few files that aren't part of
  the spec (tpm20.h) but we're including these for convenience for the
  time being. This is still very much subject to change but future changes
  will have a much lower impact.
- Rename the libraries produced:
  libtpm2sapi.so -> libtss2.so
  libtpm2tctidev.so -> libtctidev.so
  libtpm2tctisock.so -> libtctisock.so
Minor changes:
- Attempt to get some consistency in our use of either the "" or <> form
  of the include directive. For the headers that have moved we're using
  the <> form for system headers including those installed by this package.
  For headers that are internal to the project we're using the "" form.
- Cope with the removal of some 'extern' variables declared in
  previously public headers. I've only touched the cases that were
  required to move the headers, so more work will be required to clean
  this up completely and that will be tracked as part of issue #107.
- Fixup both autotools and visual studio build files.

Resolves #100
Resolves #103 

Signed-off-by: Philip Tricca <philip.b.tricca@intel.com>

### CODE REVIEW

**Comment by theopolis** [comment]
:open_mouth:

**Comment by flihp** [comment]
brace yourself :stuck_out_tongue:

**Comment by wcarthur1** [comment]
Philip,
I can't get the linux version to build the tpmclient and tpmtest.  Looks like similar errors to the ones for which I previously sent you fixes.

Windows version builds and works fine.  :)

will

**Comment by flihp** [comment]
@wcarthur1 : Can  you provide error messages from your failed build plz? Both work fine on this end so it may just be that you need a 'distclean' or something? The fixes you reference above in the last PR didn't look relevant once I diff'd them. I never used them and the PR went in fine. Might be that you've just got some pollution kicking around in your git tree?

**Comment by wcarthur1** [comment]
Philip,  here are build output and the error messages.  the errors are all related to unused variables and labels.  Are you building the DEBUG_GAP_HANDLING defined?  That would explain why you're not seeing those errors.  If you are, you don't want to build with that defined.  That's only for debugging some special cases.

g++ -DPACKAGE_NAME=\"tpm2.0-tss\" -DPACKAGE_TARNAME=\"tpm2-0-tss\" -DPACKAGE_VERSION=\"0.98\" -DPACKAGE_STRING=\"tpm2.0-tss\ 0.98\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PTHREAD=1 -DPACKAGE=\"tpm2-0-tss\" -DVERSION=\"0.98\" -I. -I../TPM2.0-TSS    -DSAPI_CLIENT -I../TPM2.0-TSS/include -I../TPM2.0-TSS/sysapi/include -I../TPM2.0-TSS/test/tpmclient -I../TPM2.0-TSS/common -I../TPM2.0-TSS/test/common/sample -I../TPM2.0-TSS/resourcemgr -I../TPM2.0-TSS/include -I../TPM2.0-TSS/common -I../TPM2.0-TSS/tcti/commonTcti -I../TPM2.0-TSS/sysapi/include -I../TPM2.0-TSS/tcti/localtpm -I../TPM2.0-TSS/include -I../TPM2.0-TSS/common -I../TPM2.0-TSS/tcti/commonTcti -I../TPM2.0-TSS/sysapi/include -O0 -Wall -Werror -ggdb3 -DDEBUG -fno-operator-names -fpermissive -MT test/tpmclient/test_tpmclient_tpmclient-tpmclient.o -MD -MP -MF test/tpmclient/.deps/test_tpmclient_tpmclient-tpmclient.Tpo -c -o test/tpmclient/test_tpmclient_tpmclient-tpmclient.o `test -f 'test/tpmclient/tpmclient.cpp' || echo '../TPM2.0-TSS/'`test/tpmclient/tpmclient.cpp
../TPM2.0-TSS/test/tpmclient/tpmclient.cpp: In function â€˜void TestStartAuthSession()â€™:
../TPM2.0-TSS/test/tpmclient/tpmclient.cpp:1480:15: error: unused variable â€˜debugGapMaxâ€™ [-Werror=unused-variable]
     UINT16 i, debugGapMax = DEBUG_GAP_MAX, debugMaxActiveSessions = DEBUG_MAX_ACTIVE_SESSIONS;
               ^
../TPM2.0-TSS/test/tpmclient/tpmclient.cpp:1480:44: error: unused variable â€˜debugMaxActiveSessionsâ€™ [-Werror=unused-variable]
     UINT16 i, debugGapMax = DEBUG_GAP_MAX, debugMaxActiveSessions = DEBUG_MAX_ACTIVE_SESSIONS;
                                            ^
../TPM2.0-TSS/test/tpmclient/tpmclient.cpp:1492:21: error: unused variable â€˜evictedSessionContextâ€™ [-Werror=unused-variable]
     TPMS_CONTEXT    evictedSessionContext;
                     ^
../TPM2.0-TSS/test/tpmclient/tpmclient.cpp:1493:18: error: unused variable â€˜evictedHandleâ€™ [-Werror=unused-variable]
     TPM_HANDLE   evictedHandle;
                  ^
../TPM2.0-TSS/test/tpmclient/tpmclient.cpp: In function â€˜void TpmTest()â€™:
../TPM2.0-TSS/test/tpmclient/tpmclient.cpp:7322:1: error: label â€˜endTestsâ€™ defined but not used [-Werror=unused-label]
 endTests:    
 ^
cc1plus: all warnings being treated as errors
make: *** [test/tpmclient/test_tpmclient_tpmclient-tpmclient.o] Error 1

**Comment by flihp** [comment]
Morning @wcarthur1. Apologies for the slow response & thanks for the build command / output. Very helpful. It looks like you're passing in some flags that are causing these errors to manifest. Specifically the combination of "-Wall -Werror" in CPPFLAGS are causing these warnings to surface and to be treated as errors.

This behavior can be reproduced against the master branch with the same flags. It may well be that we want to address these issues but since they're not unique to this PR I've created a new issue to track this problem: https://github.com/01org/TPM2.0-TSS/issues/120.

Till then are you willing to review this PR with these flags removed?

**Comment by wcarthur1** [comment]
Sure, that's okay.  Just approved it.

**Pull request merged**
