### PR TITLE
Fixed uninitialized size fields in output simple TPM2B structures.

### PR DESCRIPTION
**Pull request by wcarthur1**

### CODE REVIEW

**Comment by flihp** [comment]
Just out of curiosity: why is it size - 2?

**Comment by wcarthur1** [comment]
TPM2B’s are a sized structure, UIN16 size followed by buffer of size # of bytes.

The size field is not the size of the whole structure, just the size of the buffer, hence sizeof (TPM2B_XXXX) – 2.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by flihp** [comment]
Gotcha. So 2 is sizeof (uint16_t) to account for the structure containing an indication of it's own size. This is a lot like a TLV sequence. Makes sense to me.

**Comment by wcarthur1** [comment]
yes

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by flihp** [comment]
Cool. LGTM. Merging now.

**Pull request closed without merging**
