### PR TITLE
issue #91 test_common_code_abstraction

### PR DESCRIPTION
**Pull request by lyjbupt**
Three functions abstracted.

### CODE REVIEW

**Comment by wcarthur1** [comment]
Yingjie, that's a good start.  Do you want me to merge this pull request?  Or do you want to continue abstracting out common code on this same branch?

**Comment by lyjbupt** [comment]
Please merge it and I can fork a new one. Let's discuss more about this later.

**Comment by gwei3** [comment]
Need to be re-based.

**Comment by flihp** [comment]
I figure since this was a PR in response to a specific issue we were asking for help on and we left it sitting here for ~4 months the least we can do is do the rebase. Done and done.

@lyjbupt : thanks for the patch. Very much a step in the right direction. Apologies it took so long to get merged.

**Pull request closed without merging**
